# Generated by Django 5.0 on 2024-06-14 23:20

import django.core.files.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('observations', '0001_initial'),
        ('telescope', '0015_remove_sample_configuration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSummaryResult',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was created.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was last updated.')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='The unique identifier for this record.', unique=True)),
                ('fft_video_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='starsweep/results/')),
                ('spectrum_video_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='starsweep/results/')),
                ('configuration', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_summary_results', to='observations.configuration')),
                ('telescope', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuration_summary_results', to='telescope.telescope')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
