# Generated by Django 5.0 on 2024-06-15 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('observations', '0002_auto_20240614_2322'),
        ('telescope', '0015_remove_sample_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsummaryresult',
            name='configuration',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_results', to='observations.configuration'),
        ),
        migrations.AlterField(
            model_name='configurationsummaryresult',
            name='telescope',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_results', to='telescope.telescope'),
        ),
    ]
