# Generated by Django 5.0 on 2024-06-15 19:20

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_alter_configurationsummaryresult_configuration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationsummaryresult',
            name='fft_video_file',
            field=models.FileField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='starsweep/results/'),
        ),
        migrations.AlterField(
            model_name='configurationsummaryresult',
            name='spectrum_video_file',
            field=models.FileField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='starsweep/results/'),
        ),
    ]
