# Generated by Django 5.0 on 2024-06-15 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_auto_20240614_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='processing_state',
            field=models.CharField(blank=True, choices=[('in-progress', 'In Progress'), ('error', 'Error'), ('complete', 'Complete')], help_text='The current state of the analysis for this configuration data.', max_length=12, null=True),
        ),
    ]
