# Generated by Django 5.0.3 on 2024-04-13 21:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telescope',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was created.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was last updated.')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='The unique identifier for this record.', unique=True)),
                ('name', models.CharField(help_text='The human-recognizable name for the device.', max_length=256)),
                ('description', models.TextField(help_text='Any helpful text for the user of this device.')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], help_text='The current status of the device as reported.', max_length=30)),
                ('state', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], help_text='The current state of the device as reported.', max_length=30)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
