# Generated by Django 5.0.3 on 2024-04-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescope',
            name='description',
            field=models.TextField(default='', help_text='Any helpful text for the user of this device.'),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=9, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=9, default=None, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='state',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', help_text='The current state of the device as reported.', max_length=30),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='The current status of the device as reported.', max_length=30),
        ),
    ]
