# Generated by Django 5.0.3 on 2024-04-13 21:54

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0002_alter_telescope_description_alter_telescope_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was created.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was last updated.')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='The unique identifier for this record.', unique=True)),
                ('name', models.CharField(help_text='The human-recognizable name for the device.', max_length=256)),
                ('data', models.FileField(upload_to='observations/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='telescope',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Any helpful text for the user of this device.'),
        ),
    ]
