# Generated by Django 5.0.3 on 2024-04-13 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0003_observation_alter_telescope_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='telescope',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='telescope.telescope'),
        ),
    ]
