# Generated by Django 4.2 on 2024-04-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0004_observation_telescope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescope',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=17, default=None, max_digits=20, null=True),
        ),
    ]
