# Generated by Django 4.2 on 2024-04-17 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0006_alter_telescope_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='telescope',
            name='state_updated_at',
            field=models.DateTimeField(blank=True, default=None, help_text='The exact time when the state was last updated.', null=True),
        ),
        migrations.AddField(
            model_name='telescope',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, default=None, help_text='The exact time when the status was last updated.', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='telescope',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='telescope.telescope'),
        ),
    ]
