# Generated by Django 4.2 on 2024-04-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0007_alter_observation_options_telescope_state_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telescope',
            name='status_updated_at',
        ),
        migrations.AlterField(
            model_name='telescope',
            name='state',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='offline', help_text='The current state of the device as reported by that device.', max_length=30),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', help_text='The status of the device and whether it is actively being used.', max_length=30),
        ),
    ]
