# Generated by Django 4.2 on 2024-04-18 17:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0009_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='data',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='telescope',
        ),
        migrations.AddField(
            model_name='observation',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='When the given observation should begin.', null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='When the given observation should begin.', null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='telescopes',
            field=models.ManyToManyField(related_name='observations', to='telescope.telescope'),
        ),
        migrations.AddField(
            model_name='telescope',
            name='elevation',
            field=models.IntegerField(default=0, help_text="The device's current elevation above sea level."),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=17, default=None, help_text="The device's current latitude.", max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=17, default=None, help_text="The device's current longitude.", max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='key',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was created.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was last updated.')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='The unique identifier for this record.', unique=True)),
                ('data', models.FileField(upload_to='samples/%Y/%m/')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='telescope.observation')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
