# Generated by Django 4.2 on 2024-04-18 21:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0010_remove_observation_data_remove_observation_telescope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='end_at',
            field=models.DateTimeField(blank=True, help_text='When the given observation should begin?', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='start_at',
            field=models.DateTimeField(blank=True, help_text='When the given observation should begin?', null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='telescopes',
            field=models.ManyToManyField(help_text='The telescopes that are involved in the observation and collection of data.', related_name='observations', to='telescope.telescope'),
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was created.')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time when a record was last updated.')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='The unique identifier for this record.', unique=True)),
                ('name', models.CharField(help_text='The human-recognizable name for the observation configuration.', max_length=256)),
                ('frequency', models.PositiveBigIntegerField(default=89500000, help_text='The center frequency to capture (in Hz).')),
                ('sample_rate', models.PositiveBigIntegerField(default=2048000, help_text='The sample rate at which to collect data.')),
                ('sample_size', models.PositiveBigIntegerField(default=1024, help_text='How many data points to collect per sample.')),
                ('ppm', models.PositiveSmallIntegerField(default=1024, help_text='What PPM offset to use for the device (0 is none).')),
                ('gain', models.PositiveSmallIntegerField(default=0, help_text='The amount of gain to apply via the SDR.', validators=[django.core.validators.MaxValueValidator(100)])),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='telescope.observation')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
