# Generated by Django 4.2 on 2024-04-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0011_alter_observation_end_at_alter_observation_start_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='ppm',
            field=models.PositiveSmallIntegerField(default=0, help_text='What PPM offset to use for the device (0 is none).'),
        ),
    ]
