# Generated by Django 5.0 on 2024-04-19 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0012_alter_configuration_ppm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='observation',
            options={'ordering': ('-start_at', '-end_at')},
        ),
    ]
