# Generated by Django 5.0 on 2024-06-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0014_sample_captured_at_sample_configuration_and_more'),
        ('observations', '0002_auto_20240614_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='telescopes',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='telescope',
        ),
        migrations.DeleteModel(
            name='Configuration',
        ),
        migrations.DeleteModel(
            name='Observation',
        ),
        migrations.DeleteModel(
            name='Sample',
        ),
    ]
