# Generated by Django 5.0 on 2024-06-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('telescope', '0015_remove_sample_configuration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telescope',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
