# Generated by Django 5.0 on 2024-06-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telescope', '0016_telescope_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
