[program:astronomer]
command=/home/astronomer/venvs/astronomer/bin/python -m astronomer
directory=/mnt/ledger/radio-telescope/astronomer
autostart=true
autorestart=true
environment=TELESCOPE_ID="1",HOME_URL="https://starsweep.space/",HOME_API_HEALTH_CHECK_URL="https://starsweep.space/",HOME_AUTHORIZATION_TOKEN="test",DATABASE_LOCATION="/mnt/ledger/data/db.sqlite",CALIBRATION_PATH="/mnt/ledger/data/calibration",CAPTURE_DATA_PATH="/mnt/ledger/data/observations",CAPTURE_STATUS_PIN="25",SPECTRUM_DATA_PATH="/mnt/ledger/data/spectra",SPECTRUM_STATUS_PIN="26",TRANSMIT_STATUS_PIN="26",DOWNLINK_STATUS_PIN="11"
