[supervisorctl]

[program:astronomer]
command=/home/astronomer/venvs/astronomer/bin/python -m astronomer
directory=/mnt/ledger/radio-telescope/astronomer
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopsignal=INT
environment=HOME_URL="https://starsweep.space/",CALIBRATION_DATA_PATH="/mnt/ledger/data/calibration",CAPTURE_DATA_PATH="/mnt/ledger/data/observations",CAPTURE_STATUS_PIN="25",SPECTRUM_DATA_PATH="/mnt/ledger/data/spectra",SPECTRUM_STATUS_PIN="26",TRANSMIT_STATUS_PIN="12",DOWNLINK_STATUS_PIN="17",CALIBRATE_STATUS_PIN="16"
